repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: trailing-whitespace
    exclude: ^(.lintr/)|^(renv/)|^(vignettes/)
  - id: end-of-file-fixer
    exclude: ^(renv/)
  - id: check-yaml
  - id: check-added-large-files
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v22.1.0
  hooks:
  - id: clang-format
    exclude: '^(inst/)|(src/fast_matrix_market/)|(.*\.json)'
