// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// to_file.cpp
bool vec_to_fmm(cpp11::doubles r_vec, std::string filename);
extern "C" SEXP _fastMatMR_vec_to_fmm(SEXP r_vec, SEXP filename) {
  BEGIN_CPP11
    return cpp11::as_sexp(vec_to_fmm(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(r_vec), cpp11::as_cpp<cpp11::decay_t<std::string>>(filename)));
  END_CPP11
}
// to_file.cpp
bool mat_to_fmm(cpp11::doubles_matrix<> r_mat, std::string filename);
extern "C" SEXP _fastMatMR_mat_to_fmm(SEXP r_mat, SEXP filename) {
  BEGIN_CPP11
    return cpp11::as_sexp(mat_to_fmm(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles_matrix<>>>(r_mat), cpp11::as_cpp<cpp11::decay_t<std::string>>(filename)));
  END_CPP11
}
// to_file.cpp
bool sparse_to_fmm(cpp11::sexp input, std::string filename);
extern "C" SEXP _fastMatMR_sparse_to_fmm(SEXP input, SEXP filename) {
  BEGIN_CPP11
    return cpp11::as_sexp(sparse_to_fmm(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(input), cpp11::as_cpp<cpp11::decay_t<std::string>>(filename)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_fastMatMR_mat_to_fmm",    (DL_FUNC) &_fastMatMR_mat_to_fmm,    2},
    {"_fastMatMR_sparse_to_fmm", (DL_FUNC) &_fastMatMR_sparse_to_fmm, 2},
    {"_fastMatMR_vec_to_fmm",    (DL_FUNC) &_fastMatMR_vec_to_fmm,    2},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_fastMatMR(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
