# Generated by cpp11: do not edit by hand

cpp_fmm_to_vec <- function(filename) {
  .Call(`_fastMatMR_cpp_fmm_to_vec`, filename)
}

cpp_fmm_to_mat <- function(filename) {
  .Call(`_fastMatMR_cpp_fmm_to_mat`, filename)
}

cpp_fmm_to_sparse_Matrix <- function(filename) {
  .Call(`_fastMatMR_cpp_fmm_to_sparse_Matrix`, filename)
}

vec_to_fmm <- function(r_vec, filename) {
  .Call(`_fastMatMR_vec_to_fmm`, r_vec, filename)
}

intvec_to_fmm <- function(r_vec, filename) {
  .Call(`_fastMatMR_intvec_to_fmm`, r_vec, filename)
}

mat_to_fmm <- function(r_mat, filename) {
  .Call(`_fastMatMR_mat_to_fmm`, r_mat, filename)
}

intmat_to_fmm <- function(r_mat, filename) {
  .Call(`_fastMatMR_intmat_to_fmm`, r_mat, filename)
}

sparse_Matrix_to_fmm <- function(input, filename) {
  .Call(`_fastMatMR_sparse_Matrix_to_fmm`, input, filename)
}
